### ISSUE TITLE
`sbt compile` fails with global ammonite dependency

### ISSUE THREAD

**Issue by ankitson** [lampepfl/dotty-example-project#1]
`sbt compile` in this project fails with the following error:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.lihaoyi#ammonite_0.1-SNAPSHOT;0.7.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

when I have the following in `~/.sbt/0.13/global.sbt`:

`libraryDependencies += "com.lihaoyi" % "ammonite" % "0.7.0" % "test" cross CrossVersion.full`

It seems like the `cross CrossVersion.full` generates an invalid version in this case because there is no published SNAPSHOT version of ammonite?

I'm not sure if this is a bug or more of a pitfall to document. I'd be happy to make a PR adding warnings in the `README` if its a documentation issue.

**Comment by smarter** [comment]
Hi! Sorry for the very late response, somehow github never sent me a mail for this issue. The README now contains a warning about global plugins.
