### ISSUE TITLE
Travis CI Fails

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty-example-project#28]
Apparently, the failure is an infrastructural issue:

```
Expected feature release number in range of 9 to 13, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```

Looks like Travis suddenly stopped digesting the JDK installation command.

**Comment by SethTisue** [comment]
fixed by https://github.com/lampepfl/dotty-example-project/commit/3a0138d2e91cd760b5b23e6d13a5314ba94fdae0#diff-354f30a63fb0907d4ad57269548329e3
